### ISSUE TITLE
蓬松机器启动报错

### ISSUE THREAD

**Issue by DenNotFound** [SlimefunGuguProject/FluffyMachines#15]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [ ] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FluffyMachines/issues)，且没有找到相同的问题

### 问题描述

启动fluffymachines时出现报错且无法使用

### 复现步骤

1.添加插件
2.启动
3.出现报错

### 预期行为

应该正常启动，并且可以使用机器

### 服务器日志

https://paste.guizhanss.net/raw/ofodipeves

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![image](https://user-images.githubusercontent.com/103357331/163961090-52bfeb51-6bd8-41f9-9084-1c5e86d7a6f1.png)

### 插件版本

4

**Comment by ybw0014** [comment]
无法复现，请尝试重启服务器后再试

**Comment by DenNotFound** [comment]
多次尝试后都能打开，可能是一位op误输入reload confirm导致
