### ISSUE TITLE
[bs版本] 箱子搬运车的问题

### ISSUE THREAD

**Issue by shixinzia** [SlimefunGuguProject/FluffyMachines#42]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FluffyMachines/issues)，且没有找到相同的问题

### 问题描述

使用箱子搬运车的时候发生error

### 复现步骤

1.拿出箱子搬运车
2.右键箱子
3.产生报错

### 预期行为

箱子进入箱子搬运车

### 错误报告

https://paste.guizhanss.net/dlXw5

### 服务端软件

Purpur

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

slimefun tags 最新7b6fdc3-canary

### 插件版本

最新

**Comment by StarWishsama** [comment]
`java.lang.NoSuchMethodError:  io.github.thebusybiscuit.slimefun4.api.player.PlayerBackpack io.github.thebusybiscuit.slimefun4.api.player.PlayerProfile.createBackpack(int)`

**Comment by Xzavier0722** [comment]
应该修了
