### ISSUE TITLE
箱子搬运车搬起箱子出现问题

### ISSUE THREAD

**Issue by Mojichenfu** [SlimefunGuguProject/FluffyMachines#44]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FluffyMachines/issues)，且没有找到相同的问题

### 问题描述

箱子搬运车右键箱子后无提示，外表无变化  需要搬运的箱子无变化

当你右键空地时放下一个【空】箱子   不管大箱子小箱子 放下去都是大箱子

该bug可以刷箱子

游戏版本 1.19.4
核心版本 leaves-1.19.4.jar

### 复现步骤

右键一个箱子
在空地处放置

### 预期行为

应该将第一次右键时的箱子拿在手中搬起

### 服务端软件

其他 (请在问题描述里写明)

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

2023.06-release

### 插件版本

Build 19 zh-CN(baoad) (git 1251756)

**Comment by ybw0014** [comment]
已复现
