### ISSUE TITLE
传送装置无法正常使用

### ISSUE THREAD

**Issue by shixinzia** [SlimefunGuguProject/FluffyMachines#45]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FluffyMachines/issues)，且没有找到相同的问题

### 问题描述

使用传送装置的时候报错

### 复现步骤

1.放下传送装置
2.绑定
3.传送(出现报错无法传送)
bs版本
1.传送装置在2023.02Slimefun版本,和17版本蓬松正确使用
2.迁移后使用出现报错

### 预期行为

正确传送

### 服务器日志

https://paste.guizhanss.net/aIA2t

### 错误报告

无

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

bf5adeb-DEV

### 插件版本

21

**Comment by ybw0014** [comment]
好好好，又是不加载

**Comment by ybw0014** [comment]
已在 [0ef1745](https://github.com/SlimefunGuguProject/FluffyMachines/commit/0ef17454581dc8bf23d681cf8f45e76a92a2154b) 修复
