### ISSUE TITLE
蓬松箱子存储异常 Slimefun-DEV 版本

### ISSUE THREAD

**Issue by shixinzia** [SlimefunGuguProject/FluffyMachines#46]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FluffyMachines/issues)，且没有找到相同的问题

### 问题描述

蓬松箱子在存储的时候，存入2组相同的物品时，会迁移到右边输出槽，此时，再放入同类物品到输出槽，而不满一组时，物品会被直接销毁

### 复现步骤

1.准备个蓬松桶
2.任意物品2组出头，不到3组
3.蓬松桶放在地上
4.往输入槽放入2组物品
5.物品会被转移到输出槽
6.此时放入未满一组的物品到输出槽，物品会直接丢失
7.如果放入满一组的东西，物品会正常存入储存

### 预期行为

未满一组时，储存可正常存入

### 服务器日志

无报错日志

### 错误报告

无报错日志

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

bf5adeb-DEV

### 插件版本

22

**Comment by shixinzia** [comment]
补充说明，放的物品只能是同种未满一组的，如果是不同种，则可正常存入

**Comment by shixinzia** [comment]
补充说明:
![image](https://github.com/SlimefunGuguProject/FluffyMachines/assets/111138018/461860b0-046a-49dc-aefa-51594125f1eb)
如图所示，右边为2组筛矿的时候，左边输入未满一组的筛矿，会直接销毁，如果输入非筛矿的粘液物品，则会被正常存入
![image](https://github.com/SlimefunGuguProject/FluffyMachines/assets/111138018/cb5a28a9-a386-482d-8f25-fdeb5b20ddb6)
如图所示，如果右边是一组人造钻石，和一组筛矿的时候，输入未满一组的人造钻石或者筛矿，则都会被销毁，其他粘液物品不会
![image](https://github.com/SlimefunGuguProject/FluffyMachines/assets/111138018/27228eb9-5fa0-45de-8c50-801d1467dff5)
如图所示，如果输入的是原版物品，则不会产生这种情况，不论满不满半组都会被正常存入,证明只有粘液物品会这样

**Comment by ybw0014** [comment]
你这复现步骤6让我迷惑了半天

**Comment by shixinzia** [comment]
怎么了，确实是这样啊

**Comment by shixinzia** [comment]
如何了:(

**Comment by lyouismi** [comment]
> 如何了:(

我也遇到了这个问题，解决方案是手动把物品放在输出栏里，不要使用shift键+左键

**Comment by postyizhan** [comment]
插一嘴 这个会不会有点关系
![图片](https://github.com/SlimefunGuguProject/FluffyMachines/assets/97342038/29830f1a-6dbb-4b31-9c0c-4777d3078208)

**Comment by postyizhan** [comment]
![069a725595800d7f6b9751a06a1a41dd](https://github.com/SlimefunGuguProject/FluffyMachines/assets/97342038/f7a4a3de-7727-4555-877a-0c96c169fa3c)

**Comment by ybw0014** [comment]
现版本无法复现该问题
