### ISSUE TITLE
智能工廠 無限消耗製造

### ISSUE THREAD

**Issue by HeyNight0712** [SlimefunGuguProject/FluffyMachines#47]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/FluffyMachines/issues)，且没有找到相同的问题

### 问题描述

當 智能工廠 輸出部分 滿了 還是會持續製造

### 复现步骤

1. 放置智能工廠
2. 輸出滿了
3. 材料夠 他還是會繼續製造 並且不會 +1
4. https://cdn.discordapp.com/attachments/1122739227801694290/1128172382427820116/Minecraft_1.19.4_-__2023-07-11_11-53-17.mp4

### 预期行为

當滿了時候 會停止生產

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![image](https://github.com/SlimefunGuguProject/FluffyMachines/assets/97263430/92a188b3-24d0-439a-bce6-0269aa5b8bd7)

### 插件版本

f270b10

**Comment by StarWishsama** [comment]
Fixed at StarWishsama/Slimefun4@51c94aa
